apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  generateName: kirk-pipeline-
spec:
  serviceAccountName: workflow-creator
  entrypoint: main
  arguments:
    parameters:
    - name: repo
      value: "https://github.com/bcgov/kirk"
    - name: branch
      value: "master"
  volumeClaimTemplates:
    - metadata:
        name: work
      spec:
        storageClassName: "netapp-block-standard"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi
  # must complete in 8h (28,800 seconds)
  activeDeadlineSeconds: 28800
  # keep workflows for 1d (86,400 seconds)
  ttlStrategy:
    secondsAfterCompletion: 86400
  # delete all pods as soon as the workflow completes
  podGC:
    strategy: OnWorkflowCompletion
  parallelism: 5

  templates:
    - name: main
      steps:
        - - name: clone
            template: clone
        - - name: test
            template: test

    - name: clone
      container:
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - mountPath: /mnt/vol
            name: work
        image: alpine/git:v2.26.2
        workingDir: /mnt/vol
        args:
          - clone
          - --depth
          - "1"
          - --branch
          - "{{workflow.parameters.branch}}"
          - --single-branch
          - "{{workflow.parameters.repo}}"
          - .

    - name: test
      container:
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        image: openshift/origin-cli:latest
        command: [sh, -c]
        args: ['oc version']
        volumeMounts:
          - name: work
            mountPath: /mnt/vol
