---
  - hosts: localhost
    gather_facts: no
    vars:
      CLUSTER: "{{ lookup('env', 'CLUSTER') }}"
      LICENSE_PLATE: "{{ lookup('env', 'LICENSE_PLATE') }}"
      APP_NAME: kirk-{{ LICENSE_PLATE }}
      NS_ENVS:
      # TODO: add prod
      - dev
      - test

    tasks:
    - name: install argo
      shell: | 
        oc -n {{ LICENSE_PLATE }}-tools process -f install.yaml \
        -p APP_NAME={{ APP_NAME }} \
        -p CLUSTER={{ CLUSTER }} \
        -p LICENSE_PLATE={{ LICENSE_PLATE }} | \
        oc -n {{ LICENSE_PLATE }}-tools apply -f -

    - name: further install argo SA related
      shell: | 
        oc -n {{ LICENSE_PLATE }}-tools process -f install_sa_related.yaml \
        -p APP_NAME={{ APP_NAME }} \
        -p NS_ENV={{ item }} \
        -p LICENSE_PLATE={{ LICENSE_PLATE }} | \
        oc -n {{ LICENSE_PLATE }}-{{ item }} apply -f -
      loop: "{{ NS_ENVS}}"
