apiVersion: v1
kind: Template
metadata:
  name: argo-template
  annotations:
    description: "Basic namespace installation of Argo Workflow, requiring admin privileges on the local namespace"

labels:
  app: ${APP_NAME}-argo-workflow

objects:

- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: workflow-creator-edit-dev
    namespace: ${LICENSE_PLATE}-dev
    labels:
      app: ${APP_NAME}-argo-workflow
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
    - kind: ServiceAccount
      name: workflow-creator
      namespace: ${LICENSE_PLATE}-tools

# TODO: add rolebinding in order to deploy to prod
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: workflow-creator-edit-test
    namespace: ${LICENSE_PLATE}-test
    labels:
      app: ${APP_NAME}-argo-workflow
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
    - kind: ServiceAccount
      name: workflow-creator
      namespace: ${LICENSE_PLATE}-tools

parameters:
- name: APP_NAME
  required: true
- name: CLUSTER
  required: true
- name: LICENSE_PLATE
  required: true
