apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${app_name}-bc
labels:
  app: ${app_name}
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
      app: ${app_name}
    generation: 643
    name: ${app_name}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: ${app_name}
    name: ${app_name}${SUFFIX}
    namespace: ${license_plate}-tools
  spec:
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${app_name}:${appVersion}
    postCommit: {}
    resources: {}
    runPolicy: SerialLatestOnly
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_REPOSITORY_DIR}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: docker.io/python:3.8-alpine
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- name: app_name
  required: true
- name: license_plate
  required: true
- name: appVersion
  required: true

- name: SUFFIX
  required: false
  value: -pr-0
- name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/kirk.git
- name: SOURCE_REPOSITORY_REF
  required: true
  value: 'master'
- name: SOURCE_REPOSITORY_DIR
  required: true
  value: 'src/backend/'
