apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sa-rbac
labels:
  app: ${app_name}
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: project-set:image-puller
    namespace: ${license_plate}-tools
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: ${license_plate}-dev
    - kind: ServiceAccount
      name: default
      namespace: ${license_plate}-test
    - kind: ServiceAccount
      name: default
      namespace: ${license_plate}-prod
    - kind: ServiceAccount
      name: kirk-backup-backup-storage
      namespace: ${license_plate}-dev
    - kind: ServiceAccount
      name: kirk-backup-backup-storage
      namespace: ${license_plate}-test
    - kind: ServiceAccount
      name: kirk-backup-backup-storage
      namespace: ${license_plate}-prod
parameters:
- name: app_name
  required: true
- name: license_plate
  required: true
